### ISSUE TITLE
Command Inject creates invalid JSON when cloudinit have double quotes

### ISSUE THREAD

**Issue by i4ki** [NeowayLabs/clinit-cfn-tool#1]
Example cloud-config:

```
write_files:
  - path: /home/core/.dockercfg
    owner: core
    permissions: 0644
    content: |
      {"https://example.com/":{"auth":"lhfsldkjflks==","email":""}}
```

Reproduces:

```
clinit-cfn-tool inject -c ./cloud-config.yaml -f examples/aws-cloudformation.tpl.json
--- cut ---
 "write_files:\n",
        "  - path: /home/core/.dockercfg\n",
        "    permissions: 0644\n",
        "    owner: core\n",
        "    content: |\n",
        "      {"https://example.com/":{"auth":"lhfsldkjflks==","email":""}}\n",
--- cut --- 
```

Putting the content with encoding: base64 and encoding the string should fix the problem, but this is a known bug. The tool should escape the string encoded.
