### ISSUE TITLE
Bug extracting from template with AWS::Ref variable

### ISSUE THREAD

**Issue by i4ki** [NeowayLabs/clinit-cfn-tool#4]

**Comment by i4ki** [comment]
File to reproduce: https://s3.amazonaws.com/coreos.com/dist/aws/coreos-stable-pv.template

clinit-cfn-tool extract -i ./coreos-stable-pv.template -o ./coreos-user-data

**Comment by i4ki** [comment]
Bug fixed:

``` bash
./clinit-cfn-tool extract -i ./examples/coreos-stable-pv.template -o ./coreos-user-data
Generating file './coreos-user-data1.yaml'
cat ./coreos-user-data1.yaml
```

``` YAML
#cloud-config

coreos:
  etcd:
    discovery: {{ .Ref.DiscoveryURL }}
    addr: ${{ .Ref.AdvertisedIPAddress }}_ipv4:4001
    peer-addr: ${{ .Ref.AdvertisedIPAddress }}_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
```
